<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="6" hostname="MacBook-Pro.local" failures="1" tests="3" name="/Users/tijesuolalekan/Downloads/JavafxProject" time="5.085" errors="0" timestamp="28 Nov 2020 19:31:12 GMT">
  <testcase classname="persistence.StaffDAOTest" name="testValidateUserTrue" time="4.084"/>
  <testcase classname="persistence.StaffDAOTest" name="testValidateUser" time="0.278">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:568)
at org.testng.Assert.assertEquals(Assert.java:578)
at persistence.StaffDAOTest.testValidateUser(StaffDAOTest.java:36)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:564)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at com.intellij.rt.testng.IDEARemoteTestNG.run(IDEARemoteTestNG.java:66)
at com.intellij.rt.testng.RemoteTestNGStarter.main(RemoteTestNGStarter.java:109)
]]>
    </failure>
  </testcase> <!-- testValidateUser -->
  <testcase classname="persistence.StaffDAOTest" name="testValidateUserFalse" time="0.524"/>
  <testcase classname="persistence.StaffDAOTest" name="testUpdateLockedData" time="0.0">
    <ignored/>
  </testcase> <!-- testUpdateLockedData -->
  <testcase classname="persistence.StaffDAOTest" name="testCheckIfExists" time="0.0">
    <ignored/>
  </testcase> <!-- testCheckIfExists -->
  <testcase classname="persistence.StaffDAOTest" name="testAddUser" time="0.0">
    <ignored/>
  </testcase> <!-- testAddUser -->
  <testcase classname="persistence.StaffDAOTest" name="testGetAllStaff" time="0.0">
    <ignored/>
  </testcase> <!-- testGetAllStaff -->
  <testcase classname="persistence.StaffDAOTest" name="testGetRole" time="0.0">
    <ignored/>
  </testcase> <!-- testGetRole -->
  <testcase classname="persistence.StaffDAOTest" name="testDeleteUser" time="0.0">
    <ignored/>
  </testcase> <!-- testDeleteUser -->
</testsuite> <!-- /Users/tijesuolalekan/Downloads/JavafxProject -->
